<div class="center">
<h1>
<br>    
Welcome
<?php require 'dbconnect.php';

$id =$_SESSION['id'];
$query  =   "
                SELECT name
                FROM registered
                WHERE id_no = '$id'
            ";
$result =   mysql_query($query) or die (mysql_error());
$row    = mysql_fetch_array($result);
echo $row['name']. " !";
?>
</h1>
<ul class="p">
   
</ul>





<div class="disform">
<form name="classattend" action="#" method="post">
    <fieldset>
	<div class="field">
            <label>Select course</label>
            <select name="op">
			<?php
			 $id =$_SESSION['id'];
             $query  = "
                SELECT *
                FROM enrolled_details
                WHERE id_no = '$id'
            ";
$result =   mysql_query($query) or die (mysql_error());
while($row= mysql_fetch_array($result))
 {
                echo"<option>".$row['course_id']."</option>";
 }
                echo "</select><br><br>";
        ?></div>
        <div class="field">
            <label>Display Type</label>
            <select name="type">
                <option>Present</option>
                </select>
        </div>
        
        <div class="field">
            <br>
            <label>From</label>
            <input type="text" name="from" class="datepicker" value="" />
        </div>
        <br>
        <div class="field">
            <label>To</label>
            <input type="text" name="till" class="datepicker" value="" />

        </div>
        <div class="field" id="hidden">
            <br><label>ID</label><input type="text" name="id" value="<?php echo $_SESSION['id']; ?>" />
           
        </div>
        
        <div class="field">
        <br>
            <input type="submit" value="Show" name="save" class="Submit"/>
        </div>
    </fieldset>
</form>
</div>
<br>
<br>
<br>
<br>
<?php
if (array_key_exists('save', $_POST)) 
{
    include 'functions.php';
    $from = $_POST["from"];
    $till = $_POST["till"];
	$a=$_SESSION['id'];			
    $c_id=$_POST['op'];
    //$b = $row['course_name'];	
    $type = $_POST["type"];
    //$rollno = $_POST["id"];

    //check for date boundries
    $query =    "
                SELECT starting_date , finishing_date
                FROM course_details
                WHERE course_id='$c_id'
                ";
    $result = mysql_query($query) or die(mysql_errno());
    $row    = mysql_fetch_array($result);
    
    // http://in3.php.net/manual/en/datetime.diff.php
    
    $dt1 = new DateTime($from);
    $date_from = $dt1->format('Y-m-d'); //date
    
    $dt = new DateTime($till);
    $date_till = $dt->format('Y-m-d'); //date
        
    $today = date("Y-m-d");
	
    if (($date_from > $row['finishing_date']) or ($date_till < $row['starting_date']) )
    {
        echo "This course was for duration : ".$row['starting_date']." - ".$row['finishing_date'] ;
        echo "<br> Entered duration was out  of this scope.";
    }
    else if ($date_from > $date_till)
    {
        echo "Inconsistent entries in time window";
    }
    else if ($date_from > $today)
    {
        echo "<br> Data available from ".$row['starting_date'] ." till ".$today."<br><br>";
    }    
    else  
    {
    
        if ($date_from < $row['starting_date'] )
        {
            $from = $row['starting_date'];
            
        }
        if ($date_till > $row['finishing_date'] )
        {
            $till = $row['finishing_date'];
        }
        
        
        
        if ($date_till > $today )
        {
            $till = $today."";
            echo "<br> Data available from ".$row['starting_date'] ." ".$today."<br><br>";
        }
        
    //db connect	
    $con = db_connect();

    if (mysqli_connect_errno()) 
    {
        echo "Failed to connect to MySQL: " . mysqli_connect_error();
    } else {
        
        if($a!="")
        {
            //echo "<b><u>USER VIEW </u></b><br><br>";
                echo "For course " . $c_id . "<br><br>";
		//printing name
		$query 	= "	SELECT name FROM registered WHERE id_no='$a' ";  
		$result = mysqli_query($con,$query) or die("Error: ".mysqli_error($con));
		$row = mysqli_fetch_array($result);
		
		echo "For user ".$row['name']." ( ".$a." ) "."<br><br>";
		
                //echo "<br>".$type."<br>";	
		
                //checking if that student is enrolled for that class or not
                $query 	= "SELECT id_no , course_id FROM enrolled_details WHERE id_no='$a' AND course_id='$c_id'	";  
                $result = mysqli_query($con,$query) or die("Error: ".mysqli_error($con));
                $row = mysqli_fetch_array($result);
                if ($row['id_no'] == "")
                {
                    echo "Sorry, you are not registered for this course";
                }
				else
                {
                    //total class, extra class, cancelled class
                    class_details($con,$c_id,$from,$till);
                
                    //get the schedule for this course for entire week
                    $schedule = array();
                    $schedule = get_schedule($schedule, $c_id, $con);

                    //initialize holidays in holid array
                    $holid = array();
                    $holid = initialize_holid($holid, $from, $till, $con);
                    
                    //chart_initialize
                    //setting up the chart table
                    //actual report
                    $chart = array();    
                    $chart1= array();
                    $chart2= array();
        
                    //chart_initialize
                    $chart = initialize_chart($chart, $chart1, $schedule, $from, $till, $con , $c_id);
            
                    //classes when user is present and it's count
                    report($con,$a,$c_id,$from,$till,$type , $schedule , $holid , $chart);
                   
                }
        
				}
        else{
            //echo "<b><center><u>CLASS VIEW</u></b><br><br></center>";
            echo "For course " . $c_id . "<br><br>";

            //total class, extra class, cancelled class
            class_details($con, $c_id, $from, $till);

            $query = "  SELECT reg.name , reg.id_no 
                	FROM registered reg , enrolled_details ed  
			WHERE ed.course_id='$c_id' AND reg.id_no=ed.id_no ";
            $result = mysqli_query($con, $query) or die("Error: " . mysqli_error($con));

            // array contains names of students registered for the course
            $stu_reg_list = array();
            $stu_roll_list = array();
            while ($row = mysqli_fetch_array($result)) {
                array_push($stu_reg_list, $row['name']);
                array_push($stu_roll_list, $row['id_no']);
            }

            //calculating # attended classes for all students
            
            //get the schedule for this course for entire week
            $schedule = array();
            $schedule = get_schedule($schedule, $c_id, $con);
            
            //initialize holidays in holid array
            $holid = array();
            $holid = initialize_holid($holid, $from, $till, $con);
            
            //chart_initialize
            //setting up the chart table
            //actual report
            $chart = array();    
            $chart1= array();
            $chart2= array();
        
            //chart_initialize
            $chart = initialize_chart($chart, $chart1, $schedule, $from, $till, $con , $c_id);
            
            $i = 0;
            $stu_len = count($stu_reg_list);
            while ($i < $stu_len) {

                //printing name 
                echo "<b><br>For user " . $stu_reg_list[$i] . "</b>";
                
                //printing user's id
                echo "	(" . $stu_roll_list[$i] . ")<br><br>";

                $rollno = $stu_roll_list[$i];
                                
                //classes when user is present and it's count
                report($con,$a,$c_id,$from,$till,$type , $schedule , $holid , $chart);

                $i = $i + 1;
            }//while loop end
        }}//class view end
    }//	date boundry condition end 
    
}//if array exists part end

?>
</div>
